"""
engine/snowflake/stage_source.py

Fetches PDF documents from Snowflake external S3 stage for unstructured assessment.

For external stages, GET is not supported. Instead we use presigned URLs
generated by Snowflake to download the file content via requests.
The ZScaler cert is already configured in main.py so HTTPS works.
"""
from __future__ import annotations

import io
import os


def list_stage_files(stage: str | None = None) -> list[dict]:
    """
    List PDF files available in the Snowflake external S3 stage.
    Returns list of dicts with filename, size_kb, modified, full_path.
    """
    from engine.snowflake.connection import get_session
    session = get_session()

    stage_path = stage or os.environ.get(
        "SNOWFLAKE_PDF_S3_STAGE",
        "DQ_ACCELERATOR.UNSTRUCTURED.PDF_S3_STAGE"
    )

    rows = session.sql(f"LIST @{stage_path}").collect()

    files = []
    for r in rows:
        name     = r[0]  # full s3 path
        size     = r[1]
        last_mod = str(r[2]) if r[2] else ""
        filename = name.split("/")[-1]

        # Only include PDFs
        if not filename.lower().endswith(".pdf"):
            continue

        files.append({
            "full_path": name,
            "filename":  filename,
            "size_kb":   round((size or 0) / 1024, 1),
            "modified":  last_mod[:16],
            "stage":     stage_path,
        })

    return sorted(files, key=lambda x: x["filename"])


def download_file(filename: str, stage: str | None = None) -> io.BytesIO:
    """
    Download a PDF from the external S3 stage using a Snowflake presigned URL.
    Snowflake generates the presigned URL — we fetch it via requests.
    The ZScaler cert bundle configured in main.py handles SSL.

    Args:
        filename: Just the filename e.g. 'policy.pdf'
        stage: Full stage path e.g. 'DQ_ACCELERATOR.UNSTRUCTURED.PDF_S3_STAGE'

    Returns:
        BytesIO object ready for pdf_extractor.extract()
    """
    import requests
    from engine.snowflake.connection import get_session
    session = get_session()

    stage_path = stage or os.environ.get(
        "SNOWFLAKE_PDF_S3_STAGE",
        "DQ_ACCELERATOR.UNSTRUCTURED.PDF_S3_STAGE"
    )

    # Generate a presigned URL via Snowflake
    result = session.sql(f"""
        SELECT GET_PRESIGNED_URL(@{stage_path}, '{filename}', 3600) AS url
    """).collect()

    if not result or not result[0][0]:
        raise ValueError(f"Could not generate presigned URL for '{filename}'")

    url = result[0][0]

    # Fetch presigned URL — verify=False is safe here because:
    # 1. The URL is already cryptographically signed by Snowflake/AWS
    # 2. ZScaler SSL inspection causes cert verification failures on S3 URLs
    # 3. The content is authenticated via the HMAC signature in the URL itself
    import urllib3
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
    response = requests.get(url, timeout=60, verify=False)
    response.raise_for_status()

    buf = io.BytesIO(response.content)
    buf.name = filename
    return buf
